config/routes.rb
#app_20
#Листинг 7.3: Добавление ресурса Users в файл маршрутов. config/routes.rb 
#Листинг 8.1: Добавление ресурса для получения стандартных RESTful действий для сессий. config/routes.rb 
SampleApp::Application.routes.draw do
#get "users/new"  
 root  'static_pages#home'

 resources :lectures


 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


resources :users
resources :users do
    member do
      get :following, :followers
    end
  end

resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]
resources :relationships, only: [:create, :destroy]

 

 match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
match '/referat', to: 'static_pages#referat', via: 'get'
match '/july07', to: 'static_pages#july07', via: 'get'
match '/readme', to: 'static_pages#readme', via: 'get'



match '/tablecontent', to: 'static_pages#tablecontent', via: 'get'

#get "static_pages/tablecontent"
#get "static_pages/referat"
#get "static_pages/help"
#get "static_pages/July07"

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
 belongs_to :user
  validates :user_id, presence: true
  validates :lectname, presence: true, length: { maximum: 140 }
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:lectname, :lecttext)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lectname %><br>
    <%= f.text_field :lectname %>
  </div>
  <div class="field">
    <%= f.label :lecttext %><br>
    <%= f.text_field :lecttext %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<h1>Listing lectures</h1>

<table>
  <thead>
    <tr>
      <th>Lectname</th>
      <th>Lecttext</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.lectname %></td>
        <td><%= lecture.lecttext %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lectname:</strong>
  <%= @lecture.lectname %>
</p>

<p>
  <strong>Lecttext:</strong>
  <%= @lecture.lecttext %>
</p>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>