config/routes.rb
#app_20
#Листинг 7.3: Добавление ресурса Users в файл маршрутов. config/routes.rb 
#Листинг 8.1: Добавление ресурса для получения стандартных RESTful действий для сессий. config/routes.rb 
SampleApp::Application.routes.draw do
#get "users/new"  
 root  'static_pages#home'

 resources :lectures


 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


resources :users
resources :users do
    member do
      get :following, :followers
    end
  end

resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]
resources :relationships, only: [:create, :destroy]

 

 match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
match '/referat', to: 'static_pages#referat', via: 'get'
match '/july07', to: 'static_pages#july07', via: 'get'
match '/readme', to: 'static_pages#readme', via: 'get'



match '/tablecontent', to: 'static_pages#tablecontent', via: 'get'

#get "static_pages/tablecontent"
#get "static_pages/referat"
#get "static_pages/help"
#get "static_pages/July07"

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  end

app/views/layouts/''application.html.erb
#Листинг 7.25:
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
     <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>   #css s
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      #<% flash.each do |key, value| %>
   #<% flash.each do |message_type, message| %>
      </div>
<div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/'application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '#' %></li>
              <li><%= link_to "Help",    '#' %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Referat", referat_path %></li> 
     <li><%= link_to "July07", july07_path %></li>
	 <li><%= link_to "Readme", readme_path %></li>
  
  



<!-- Простой маршрут  <li><%#= link_to "Referat",    "/static_pages/referat" %></li>    -->

	<li><%= link_to "TableofContents", tablecontent_path %></li>

<!-- <li><%#= link_to "tablecontent",    "/static_pages/tablecontent" %></li>    -->

      <li><a href="http://news.railstutorial.org/">News</a></li>





<!--   <a href="/static_pages/about">About</a>    -->



    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--Листинг 9.27. Jen20  app/views/layouts/_header.html.erb  
Листинг 9.4: Добавление URL к ссылке “Settings” в шаблоне сайта. app/views/layouts/_header.html.erb -->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Главная", root_path %></li>
          <li><%= link_to "Помощь", help_path %></li>

          <% if signed_in? %>
            <li><%= link_to "Пользователи", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- app_Jen20 -->
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>